version: 1
!!!versionName: "1.0"
packageName: sumLimit
appName: "SumLimit"
appUUID: "????"


capabilities:
  - storage
  - http
  - event-bus
  - receipts

plugins:
  - name: excess
    moments:
      - событие перед закрытием чека и переходом к оплате
    point: before
    behavior: out-of-range.js

views:
  - name: excess-lim
    source: warning.html
    scripts: warning.js
    styles:
      - "*.css"
